lvyx:
  system:
    active: "test"
    file-path: "D:/CommunitySystem"
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/l_community?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource