lvyx:
  system:
    active: "test" # 开启测试环境
    test-captcha-code: "0715" # 测试环境验证码，方便登录
    file-path: "/app/community_system_file" # 文件存储路径
    logo-path: "/app/community_system_file/STATIC/logo/logo.png" # logo存储路径